zshrc use antigen by oh-my-zsh

diff --git a/hiddenrc/zshrc b/hiddenrc/zshrc
--- a/hiddenrc/zshrc
+++ b/hiddenrc/zshrc
@@ -1,211 +1,145 @@
-# Enable Powerlevel10k instant prompt. Should stay close to the top of ~/.zshrc.
-# Initialization code that may require console input (password prompts, [y/n]
-# confirmations, etc.) must go above this block; everything else may go below.
-if [[ -r "${XDG_CACHE_HOME:-$HOME/.cache}/p10k-instant-prompt-${(%):-%n}.zsh" ]]; then
-  source "${XDG_CACHE_HOME:-$HOME/.cache}/p10k-instant-prompt-${(%):-%n}.zsh"
-fi
-
 # Antigen: https://github.com/zsh-users/antigen
 ANTIGEN="$HOME/.local/bin/antigen.zsh"
 
 # Install antigen.zsh if not exist
 if [ ! -f "$ANTIGEN" ]; then
-	echo "Installing antigen ..."
-	[ ! -d "$HOME/.local" ] && mkdir -p "$HOME/.local" 2> /dev/null
-	[ ! -d "$HOME/.local/bin" ] && mkdir -p "$HOME/.local/bin" 2> /dev/null
-	# [ ! -f "$HOME/.z" ] && touch "$HOME/.z"
-	URL="http://git.io/antigen"
-	TMPFILE="/tmp/antigen.zsh"
-	if [ -x "$(which curl)" ]; then
-		curl -L "$URL" -o "$TMPFILE"
-	elif [ -x "$(which wget)" ]; then
-		wget "$URL" -O "$TMPFILE"
-	else
-		echo "ERROR: please install curl or wget before installation !!"
-		exit
-	fi
-	if [ ! $? -eq 0 ]; then
-		echo ""
-		echo "ERROR: downloading antigen.zsh ($URL) failed !!"
-		exit
-	fi;
-	echo "move $TMPFILE to $ANTIGEN"
-	mv "$TMPFILE" "$ANTIGEN"
+  echo "Installing antigen ..."
+  [ ! -d "$HOME/.local" ] && mkdir -p "$HOME/.local" 2> /dev/null
+  [ ! -d "$HOME/.local/bin" ] && mkdir -p "$HOME/.local/bin" 2> /dev/null
+  # [ ! -f "$HOME/.z" ] && touch "$HOME/.z"
+  URL="http://git.io/antigen"
+  TMPFILE="/tmp/antigen.zsh"
+  if [ -x "$(which curl)" ]; then
+    curl -L "$URL" -o "$TMPFILE"
+  elif [ -x "$(which wget)" ]; then
+    wget "$URL" -O "$TMPFILE"
+  else
+    echo "ERROR: please install curl or wget before installation !!"
+    exit
+  fi
+  if [ ! $? -eq 0 ]; then
+    echo ""
+    echo "ERROR: downloading antigen.zsh ($URL) failed !!"
+    exit
+  fi;
+  echo "move $TMPFILE to $ANTIGEN"
+  mv "$TMPFILE" "$ANTIGEN"
 fi
 
-
-
-# Load local bash/zsh compatible settings
-INIT_SH_NOFUN=1
-INIT_SH_NOLOG=1
-DISABLE_Z_PLUGIN=1
-
-# exit for non-interactive shell
-[[ $- != *i* ]] && return
-
-# WSL (aka Bash for Windows) doesn't work well with BG_NICE
-[ -d "/mnt/c" ] && [[ "$(uname -a)" == *Microsoft* ]] && unsetopt BG_NICE
-
 # Initialize command prompt
-export PS1="%n@%m:%~%# "
+if [[ -z $DISPLAY ]]; then
+  export EDITOR='vim'
+  export BROWSER='w3m'
+else
+  export EDITOR='nvim'
+  export BROWSER='chromium'
+fi
+
+export FZF_DEFAULT_OPTS='--height 40% --reverse --multi'
+
+[ -z "$PS1" ] && export PS1="%n@%m:%~%# "
+[ -z "$EDITOR" ] && export EDITOR='vim'
+[ -z "$VISUAL" ] && export VISUAL='vim'
+[ -z "$TERM" ] && export TERM="xterm-256color"
 
 # Initialize antigen
 source "$ANTIGEN"
 
-# Setup dir stack
-DIRSTACKSIZE=10
-setopt autopushd pushdminus pushdsilent pushdtohome pushdignoredups cdablevars
-alias d='dirs -v | head -10'
-
-# Disable correction
-unsetopt correct_all
-unsetopt correct
-DISABLE_CORRECTION="true"
-
-# Enable 256 color to make auto-suggestions look nice
-export TERM="xterm-256color"
-
-ZSH_AUTOSUGGEST_USE_ASYNC=1
-
-# Declare modules
-zstyle ':prezto:*:*' color 'yes'
-zstyle ':prezto:module:editor' key-bindings 'emacs'
-zstyle ':prezto:module:git:alias' skip 'yes'
-zstyle ':prezto:module:prompt' theme 'redhat'
-zstyle ':prezto:module:prompt' pwd-length 'short'
-zstyle ':prezto:module:terminal' auto-title 'yes'
-zstyle ':prezto:module:autosuggestions' color 'yes'
-zstyle ':prezto:module:python' autovenv 'yes'
-zstyle ':prezto:load' pmodule \
-	'environment' \
-	'editor' \
-	'history' \
-	'git' \
-	'utility' \
-	'completion' \
-	'history-substring-search' \
-	'autosuggestions' \
-	'prompt' \
-
-	# 'autosuggestions' \
-
 # Initialize prezto
-antigen use prezto
-
+# antigen use prezto
+antigen use oh-my-zsh
+# antigen use http://git.grml.org/f/grml-etc-core/etc/zsh/zshrc
 
 # default bundles
-antigen bundle rupa/z z.sh
-antigen bundle Vifon/deer
+# antigen bundle git
+# antigen bundle rupa/z z.sh
+# antigen bundle sinetoami/web-search
+antigen bundle z
+antigen bundle web-search
+antigen bundle romkatv/archive
 antigen bundle zdharma/fast-syntax-highlighting
-# antigen bundle zsh-users/zsh-autosuggestions
-
-antigen bundle willghatch/zsh-cdr
+antigen bundle zsh-users/zsh-autosuggestions
+# antigen bundle zsh-users/zsh-completions
+# antigen bundle Vifon/deer
+# antigen bundle willghatch/zsh-cdr
 # antigen bundle zsh-users/zaw
-antigen theme romkatv/powerlevel10k
 
-# check login shell
-if [[ -o login ]]; then
-	[ -f "$HOME/.config/custom-login/login.sh" ] && source "$HOME/.config/custom-login/login.sh"
-	[ -f "$HOME/.config/custom-login/login.zsh" ] && source "$HOME/.config/custom-login/login.zsh"
-fi
-
-# syntax color definition
-ZSH_HIGHLIGHT_HIGHLIGHTERS=(main brackets pattern)
-
-typeset -A ZSH_HIGHLIGHT_STYLES
-
-# ZSH_HIGHLIGHT_STYLES[command]=fg=white,bold
-# ZSH_HIGHLIGHT_STYLES[alias]='fg=magenta,bold'
-
-ZSH_HIGHLIGHT_STYLES[default]=none
-ZSH_HIGHLIGHT_STYLES[unknown-token]=fg=009
-ZSH_HIGHLIGHT_STYLES[reserved-word]=fg=009,standout
-ZSH_HIGHLIGHT_STYLES[alias]=fg=cyan,bold
-ZSH_HIGHLIGHT_STYLES[builtin]=fg=cyan,bold
-ZSH_HIGHLIGHT_STYLES[function]=fg=cyan,bold
-ZSH_HIGHLIGHT_STYLES[command]=fg=white,bold
-ZSH_HIGHLIGHT_STYLES[precommand]=fg=white,underline
-ZSH_HIGHLIGHT_STYLES[commandseparator]=none
-ZSH_HIGHLIGHT_STYLES[hashed-command]=fg=009
-ZSH_HIGHLIGHT_STYLES[path]=fg=214,underline
-ZSH_HIGHLIGHT_STYLES[globbing]=fg=063
-ZSH_HIGHLIGHT_STYLES[history-expansion]=fg=white,underline
-ZSH_HIGHLIGHT_STYLES[single-hyphen-option]=none
-ZSH_HIGHLIGHT_STYLES[double-hyphen-option]=none
-ZSH_HIGHLIGHT_STYLES[back-quoted-argument]=none
-ZSH_HIGHLIGHT_STYLES[single-quoted-argument]=fg=063
-ZSH_HIGHLIGHT_STYLES[double-quoted-argument]=fg=063
-ZSH_HIGHLIGHT_STYLES[dollar-double-quoted-argument]=fg=009
-ZSH_HIGHLIGHT_STYLES[back-double-quoted-argument]=fg=009
-ZSH_HIGHLIGHT_STYLES[assign]=none
+case ${TERM} in
+  xterm*|rxvt*|Eterm|aterm|kterm|gnome*)
+    antigen theme romkatv/powerlevel10k
+    ;;
+  *)
+    antigen theme ys
+    ;;
+esac
 
 antigen apply
 
-# work around: fast syntax highlighting may crash zsh without this
-FAST_HIGHLIGHT[chroma-git]="chroma/-ogit.ch"
+autoload -Uz archive lsarchive unarchive edit-command-line
 
-# options
-unsetopt correct_all
-unsetopt share_history
-setopt prompt_subst
+zle -N edit-command-line
 
-setopt BANG_HIST                 # Treat the '!' character specially during expansion.
-setopt INC_APPEND_HISTORY        # Write to the history file immediately, not when the shell exits.
-# setopt SHARE_HISTORY             # Share history between all sessions.
-setopt HIST_EXPIRE_DUPS_FIRST    # Expire duplicate entries first when trimming history.
-setopt HIST_IGNORE_DUPS          # Don't record an entry that was just recorded again.
-setopt HIST_IGNORE_ALL_DUPS      # Delete old recorded entry if new entry is a duplicate.
-setopt HIST_FIND_NO_DUPS         # Do not display a line previously found.
-setopt HIST_IGNORE_SPACE         # Don't record an entry starting with a space.
-setopt HIST_SAVE_NO_DUPS         # Don't write duplicate entries in the history file.
-setopt HIST_REDUCE_BLANKS        # Remove superfluous blanks before recording entry.
-setopt HIST_VERIFY # Don't execute immediately upon history expansion.
+my-ctrl-z() {
+if [[ $#BUFFER -eq 0 ]]; then
+  BUFFER="fg"
+  zle accept-line -w
+else
+  zle push-input -w
+  zle clear-screen -w
+fi
+}
+zle -N my-ctrl-z
 
-# setup for deer
-autoload -U deer
-zle -N deer
+toggle-sudo() {
+[[ -z "$BUFFER" ]] && zle up-history -w
+if [[ "$BUFFER" != "sudo "* ]]; then
+  BUFFER="sudo $BUFFER"
+  CURSOR=$(( CURSOR + 5 ))
+else
+  BUFFER="${BUFFER#sudo }"
+fi
+}
+zle -N toggle-sudo
 
-# default keymap
-bindkey '\eh' backward-char
-bindkey '\el' forward-char
-bindkey '\ej' down-line-or-history
-bindkey '\ek' up-line-or-history
-bindkey '\eH' backward-word
-bindkey '\eL' forward-word
-bindkey '\eJ' beginning-of-line
-bindkey '\eK' end-of-line
+toggle-ddg() {
+[[ -z "$BUFFER" ]] && zle up-history -w
+if [[ "$BUFFER" != "ddg "* ]]; then
+  BUFFER="ddg $BUFFER"
+  CURSOR=$(( CURSOR + 5 ))
+else
+  BUFFER="${BUFFER#ddg }"
+fi
+}
+zle -N toggle-ddg
 
-bindkey '\e[1;3D' backward-word
-bindkey '\e[1;3C' forward-word
-bindkey '\e[1;3A' beginning-of-line
-bindkey '\e[1;3B' end-of-line
+function mdg() { [[ $# == 1 ]] && mkdir -p -- "$1" && cd -- "$1" }
+compdef _directories mdg
 
-bindkey '\ev' deer
+
 bindkey -s '\eo' 'cd ..\n'
 bindkey -s '\e;' 'll\n'
-bindkey -s '\ee' 'vim\n'
 bindkey -s '\eu' 'ranger\n'
 bindkey -s '\e-' 'cd -\n'
 bindkey -s '\e0' 'cd ~\n'
 bindkey -s '\ep' 'ncdu\n'
+bindkey -s '\ea' 'bc -l\n'
+bindkey -s '^t' 'cd "$(dirname "$(fzf)")"\n'
+# Edit line in vim with ctrl-e:
+bindkey '\ee' edit-command-line
+bindkey '\es' toggle-sudo
+bindkey '\ei' toggle-ddg
+bindkey '^z'  my-ctrl-z
 
-
-# Disable correction
-unsetopt correct_all
-unsetopt correct
-DISABLE_CORRECTION="true"
-
-# completion detail
-zstyle ':completion:*:complete:-command-:*:*' ignored-patterns '*.pdf|*.exe|*.dll'
-zstyle ':completion:*:*sh:*:' tag-order files
-zstyle ':completion:*' rehash true
-# load custom config
-
-[ -f "$HOME/.config/custom-login/local.zsh" ] && source "$HOME/.config/custom-login/local.zsh"
-[ -f "$HOME/.config/custom-login/func.sh" ] && source "$HOME/.config/custom-login/func.sh"
-
-
+# p10k configure
+# POWERLEVEL9K_DISABLE_CONFIGURATION_WIZARD=true
+[ -f ~/.p10k.zsh ] && source ~/.p10k.zsh
+# ~/.fzf/install -all
 [ -f ~/.fzf.zsh ] && source ~/.fzf.zsh
 
-# To customize prompt, run `p10k configure` or edit ~/.p10k.zsh.
-[[ ! -f ~/.p10k.zsh ]] || source ~/.p10k.zsh
+# source other file if exit
+[ -f ~/.aliases ] && source ~/.aliases
+
+# source other shell file
+for confile (~/.config/custom-login/*.zsh); do
+  source $confile
+done
